services:
  docker:
    image: docker:dind
    container_name: jenkins_docker
    privileged: true
    ports:
      - 2376:2376
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./certs:/certs/client
    command: ["--storage-driver", "overlay2"]
    restart: always

  jenkis:
    container_name: jenkins
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./certs:/certs/client:ro
    depends_on:
      - docker